/* -*- lexical-binding: t; -*- */
/*
;;  This program is free software; you can redistribute it and/or modify 
;;  it under the terms of the GNU General Public License as published by         
;;  the Free Software Foundation; either version 2 of the License, or            
;;  (at your option) any later version.                                  

;;  This program is distributed in the hope that it will be useful,              
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of               
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                
;;  GNU General Public License for more details.         

;;  dgeom package for Maxima.
;;  Eric Majzoub, 2026
*/

if get('dgeom,'dgeom_version)#false then error("Package dgeom already loaded!")$
put('dgeom,'0.1,'dgeom_version)$

load("dgeom.lisp") $
load("dg_defs.mac")$
load("dg_util.mac")$
/* load the documentation */
load("dgeom-index.lisp")$
load("dgeom-index-html.lisp")$

/********************/
/* Global variables */
/********************/
dg_minkowski:1;
scrootg:0;
cords_ot:0;
lg:0; /* for compatibility with ctensor */
g:0;
dim:0;
declare_index_properties(mcs,[postsubscript,postsubscript,postsuperscript]);

/*******************/
/* tellsimp rules  */
/*******************/
/* The following rule institutes dd=0, so that diff(del(X))=0 */
matchdeclare(X,true,Y,true)$
tellsimpafter(Y*'diff(del(X),X,1)*del(X),0)$


no_init_messg():=disp("Do NOT run dg_metric(init), the metric is already defined.")$
/************************************/
/* NOTE: Always call dg_coords first!!!

cords_in is coordinates IN
cords_tr is the transformation
cords_ot is coordinates OUT

*/
dg_cords(crds):=block(
  dg_minkowski:1, /* set to 1 for all coordinate systems by default */
  if crds='cart2d then
   ( cords_in:[x,y],
     cords_tr:[x,y],
     cords_ot:[x,y] )
  else if crds='cart3d then
   ( cords_in:[x,y,z],
     cords_tr:[x,y,z],
     cords_ot:[x,y,z] )
  else if crds='xyz_to_spher then
   ( cords_in:[x,y,z],
     cords_tr:[r*sin(theta)*cos(phi),r*sin(theta)*sin(phi),r*cos(theta)],
     cords_ot:[r,theta,phi],
     assume(r>0,theta>0,theta<%pi) )
  else if crds='xyz_to_spher2 then
   ( cords_in:[x,y,z],
     cords_tr:[r*cos(phi)*cos(theta),r*cos(phi)*sin(theta),r*sin(phi)],
     cords_ot:[r,theta,phi],
     assume(r>0,phi>0,phi<%pi) )
  else if crds='xyz_to_pro_spher then
   ( cords_in:[x,y,z],
     cords_tr:[sinh(chi)*sin(theta)*cos(phi),sinh(chi)*sin(theta)*sin(phi),
               cosh(chi)*cos(theta)],
     cords_ot:[chi,theta,phi],
     assume(chi>0,theta>0,theta<%pi) )
  else if crds='xyz_to_paraboloid then
   ( cords_in:[x,y,z],
     cords_tr:[u*v*cos(phi),u*v*sin(phi),1/2*(u^2-v^2)],
     cords_ot:[u,v,phi],
     assume(phi>=0) )
  else if crds='txyz_to_spher then
   ( dg_minkowski: -1,
     cords_in:[t,x,y,z],
     cords_tr:[t,r*sin(theta)*cos(phi),r*sin(theta)*sin(phi),r*cos(theta)],
     cords_ot:[t,r,theta,phi],
     assume(r>0,theta>0,theta<%pi) )
   else if crds='xyz_to_cyl then
   ( cords_in:[x,y,z],
     cords_tr:[r*cos(phi),r*sin(phi),z],
     cords_ot:[r,phi,z],
     assume(r>0) )
   else if crds='xy_to_polar then
   ( cords_in:[x,y],
     cords_tr:[r*cos(theta),r*sin(theta)],
     cords_ot:[r,theta],
     assume(r>0) )
   else if crds='xy_to_exp1 then
   ( cords_in:[x,y],
     cords_tr:[s*exp(t),s*exp(-t)],
     cords_ot:[s,t],
     assume(t>0) )
   else if crds='xy_to_uv2 then
   ( cords_in:[x,y],
     cords_tr:[u,v^2],
     cords_ot:[u,v] )
   else if crds='mink2d then
   ( dg_minkowski: -1,
     cords_in:[t,x],
     cords_tr:[t,x],
     cords_ot:[t,x] )
   else if crds='mink4d then
   ( dg_minkowski: -1,
     cords_in:[t,x,y,z],
     cords_tr:[t,x,y,z],
     cords_ot:[t,x,y,z] )
   else if crds='rindler then
   ( dg_minkowski: -1,
     cords_in:[t,x],
     cords_tr:[rho*sinh(omega),rho*cosh(omega)],
     cords_ot:[omega,rho],
     assume(rho>0) )
   else if crds='schwarzschild then
   ( no_init_messg(),
     cords_in:[t,r,theta,phi],
     cords_ot:cords_in,
     declare([G,M],constant),
     assume(r>0,theta>0,theta<%pi,phi>0,phi<2*%pi,G>0,M>0),
     ds2: -(1-2*G*M/r)*del(t)^2+1/(1-2*G*M/r)*del(r)^2+r^2*del(theta)^2+r^2*sin(theta)^2*del(phi)^2,
     g:lg: ds2_to_lg(ds2,cords_in) )
   else if crds='kerr then
   ( no_init_messg(),
     cords_in:[t,rho,theta,phi],
     cords_ot:cords_in,
     declare([M,a,J,G],constant),
     assume(r>0,theta>0,theta<%pi,phi>0,phi<2*%pi,G>0,J>0,M>0),
     DD:r^2-2*G*M*r+a^2,
     ds2: -(1-2*G*M*r/rho^2)*del(t)^2-4*G*M*r*a*sin(theta)^2/rho^2*del(t)*del(phi)+rho^2/DD*del(r)^2+rho^2*del(theta)^2+(r^2+a^2+2*G*M*r*a^2*sin(theta)^2/rho^2)*sin(theta)^2*del(phi)^2,
     constraint_eq1: rho^2=r^2+a^2*cos(theta)^2,
     constraint_eq2: DD,
     g:lg: ds2_to_lg(ds2,cords_in) )
   else if crds='kruskal then
   ( no_init_messg(),
     cords_in:[T,X,theta,phi],
     cords_ot:cords_in,
     declare([M,G],constant),
     assume(r>0,theta>0,theta<%pi,phi>0,phi<2*%pi,G>0,M>0),
     ds2: (32*G^3*M^3/r)*exp(-r/(2*G*M))*(-del(T)^2+del(X)^2)+r^2*del(theta)^2+r^2*sin(theta)^2*del(phi)^2,
     constraint_eq:(r/(2*M)-1)*exp(r/(2*M))=X^2-T^2,
     g:lg: ds2_to_lg(ds2,cords_in) )
   else if crds='eddfink then
   ( no_init_messg(),
     cords_in:[v,r,theta,phi],
     cords_ot:cords_in,
     declare([M,G],constant),
     assume(r>0,theta>0,theta<%pi,phi>0,phi<2*%pi,G>0,M>0),
     ds2: -(1-2*G*M/r)*del(v)^2+2*del(v)*del(r)+r^2*del(theta)^2+r^2*sin(theta)^2*del(phi)^2,
     g:lg: ds2_to_lg(ds2,cords_in) )
   else
   ( print("The following predefined coordinate systems are available:"),
     print("  cart2d, cart3d, xyz_to_spher, xyz_to_pro_spher, xyz_to_spher2, xyz_to_paraboloid"),
     print("  txyz_to_spher, xyz_to_cyl, xy_to_polar, xy_to_exp1, xy_to_uv2, mink2d, mink4d, rindler"),
     print("  schwarzschild, kerr, eddfink, kruskal.") ),
   done
)$

/****************/
/* run_checks() */
/****************/
run_checks():=block(
  if listp( cords_in )=false then (print("Must set cords_in !!"), return(false)),
  if listp( cords_tr )=false then (print("Must set cords_tr !!"), return(false)),
  if listp( cords_ot )=false then (print("Must set cords_ot !!"), return(false)),
  true
);

/**********************/
/*  set_ctensor_vars  */
/**********************/
set_ctensor_vars(trn):=block([],
  run_checks(),
  cframe_flag:false,
  dim:length(cords_ot),
  ctlist:makelist(cords_tr[i],i,dim),
  ctlist:append(ctlist,[cords_ot]),
  if get('ctensor,'version)=false then load(ctensor),
  ct_coordsys(ctlist),
  /* ct_coodsys calls cmetric() which is equivalent to our dg_metric(init),
     so we have to call dg_metric() again if trn='cnvrt to get the correct
     metric. */
  dg_metric(trn),
  lg:trigsimp(lg),
  display(ctlist)
);

/**********************/
/*  get_ctensor_vars  */
/**********************/
get_ctensor_vars():=block([],
  cords_ot:ct_coords, cords_in:ct_coords, cords_tr:ct_coords,
  disp(cords_ot),
  lg:trigsimp(lg),
  g:lg,
  print("done")
);


/*****************/
/* show_cords()  */
/*****************/
show_cords():=block(
  if run_checks()=false then return("Coordinates not defined."),
  display(cords_in),
  display(cords_tr),
  display(cords_ot),
  display(dg_minkowski)
);

/************/
/* rowmag() */
/************/
/* function to return the magnitude of a row
of a matrix */
rowmag(M,n):=block([dim:length(M),i,j,mgsq:0],
    for i: 1 thru dim do
        mgsq: mgsq + M[n,i]^2,
    mgsq: trigsimp(mgsq),
    sqrt(mgsq)
);

/**************/
/* row_norm() */
/**************/
/* Normalize the rows of a matrix */
row_norm(M):=block([dim,rmag,R],
  dim:length(M),
  rmag:zeromatrix(1,dim),
  R:zeromatrix(dim,dim),

  for i: 1 thru dim do /* compute the row magnitudes */
    rmag[1,i]:rowmag(M,i),
  /* Normalize the row lengths */
  for i:1 thru dim do
    for j: 1 thru dim do
      if rmag[1,i]#0 then R[i,j]:M[i,j]/rmag[1,i],
  R
);

/*****************/
/* dg_jacobian() */
/*****************/
dg_jacobian([args]):=block([N,ishow],
  ishow: if args=[] then 0 else first(args),
  run_checks(),
  N:length(cords_in),
  J:zeromatrix(N,N),
  Jinv:zeromatrix(N,N),
  
  /* construct the Jacobian matrix */
  for i: 1 thru N do
    for j: 1 thru N do
      J[i,j]: diff( cords_tr[i] , cords_ot[j] ),

  /* compute the inverse and transpose of J */
    Jinv: trigsimp( invert(J) ),
    Jt: trigsimp( transpose(J) ),
    if ishow=1 then return(J),
    if ishow=2 then return(Jinv),    
    done
);

/***************/
/* dg_derivs() */
/***************/
/*
Call dg_derivs to compute the partial derivatives
in the new coordinates.

Invoke the derivatives by...
d_dx( ev(d_dx(r),diff) ),diff;

*/
dg_derivs():=block([N],
  run_checks(),
  N:length(cords_in),
  dg_jacobian(0),
  
  /* construct the differential operators */
  for i: 1 thru N do
    block([tmp],
      block([ffin:0,F],
        for j: 1 thru N do
        ffin: ffin + J[j,i] * 'diff(F,cords_ot[j]),
        ffin: trigsimp(ffin),
        tmp: cords_in[i],
        tmp: concat(d_d,tmp),
        /* display(tmp),
        display(ff), */
        define( funmake(tmp,[F]) , ffin) ),
      block([ffot:0,F],
        for j: 1 thru N do
        ffot: ffot + Jinv[j,i] * 'diff(F,cords_in[j]),
        ffot: trigsimp(ffot),
        tmp: cords_ot[i],
        tmp: concat(d_d,tmp),
        /* display(tmp),
        display(ff), */
        define( funmake(tmp,[F]) , ffot) )
     )
);


/***************/
/* dg_metric() */
/***************/
/*computes the metric in the new coordinates */
is_eq(expr) := if not mapatom(expr) and op(expr) = "=" then 1 else 0;

dg_metric(trn):=block([N,sol],
  N: length(cords_in),

  /* if trn = init, assume the metric is trivial */
  if trn='init then block(
  ds2_in:0,
  ds2_in: dg_minkowski * diff(cords_in[1])^2, /* in case minkowski */
  for i: 2 thru N do ds2_in: ds2_in + diff(cords_in[i])^2,
  ds2_in: trigsimp(ds2_in)
  )
  else if trn='cnvrt or trn='cnvrt2 then
    ds2_in: sum( sum( lg_in[i,j] * del(cords_in[i]) * del(cords_in[j]), i, 1, N ), j, 1, N)
  else print("argument must be init or cnvrt or cnvrt2"),
  display(ds2_in),

  ds2:0,
  if trn='init then block(
    ds2: dg_minkowski * diff(cords_tr[1])^2, /* in case minkowski */
    for i: 2 thru N do ds2: ds2 + diff(cords_tr[i])^2 )
  else if trn='cnvrt then block(
    ds2_in: sum( sum( lg_in[i,j] * diff(cords_tr[i]) * diff(cords_tr[j]), i, 1, N ), j, 1, N),
    ds2: subst(map("=",cords_in,cords_tr),ds2_in) )
  else if trn='cnvrt2 then block(
    ds2:ds2_in,
    for i:1 thru N do if is_eq(cords_tr[i])#0 then ds2: subst( solve(diff(cords_tr[i]),del(cords_in[i])), ds2 )
  ),

  ds2:expand(ds2),
  for i:1 thru N do ds2:collectterms(ds2,del( args(cords_ot)[i] ) ),
  for i:1 thru N do ds2:substpart( trigsimp(part(ds2,i)), ds2,i),
  for i:1 thru N do ds2:substpart( trigsimp(part(ds2,i)), ds2,i), /* yes, do this twice */

g: zeromatrix(N,N),
  for i: 1 thru N do
    for j: 1 thru N do
      g[i,j]: coeff( expand( ds2 ) , del(args(cords_ot)[i]) * del(args(cords_ot)[j]) ),
      g: trigsimp(g), lg:g,
      detg: determinant(g),
      if detg#0 then ug: g^^(-1) else error("g is singular!"),
      scrootg: sqrt( detg ),

  display( ds2 )
)$

/****************/
/* dg_curl()    */
/****************/
/* this code computes the curl two different ways. (1) "physical
basis", the way vector calc textbooks do it. the 'scale factor' which
is h_i = sqrt(g[i,i]).  You have to transform the coordinates before
differentiating, and also the whole component of the curl
afterwards. This is shown in both factors of h_i below in curcomp.
(2) the "coordinate basis" using tensors */

curcomp(i):=block([tmp], tmp: -sum( sum(lc(i,j,k)*diff(
sqrt(g[j,j])*W[j], args(tolist)[k] ),j,1,N), k,1,N),
sqrt(g[i,i])*tmp/scrootg )$

cont2cov(k):=sum(g[k,l]*W[l],l,1,N) $
covdiff(j,k):=diff(W[j],args(tolist)[k])-sum(mcs[i,j,k]*cont2cov(k),k,1,N) $
curcomp2(i):=block(
  sum( sum( lc(i,j,k)*covdiff(j,k) ,k,1,N) /scrootg ,j,1,N)
)$

/* Curl in the new coordinates */
/* Need to call dg_metric(); first for this to work */
dg_curl(ff):=block([W,N,tolist:cords_ot,tmp],
    if ff#1 and ff#2 then return(print("Arg must be (1) physical basis or (2) coordinate basis")),
  dg_metric(init),
  N:length(tolist),
  if N#3 then return(print("Curl limited to d=3")),
  for i: 1 thru N do ( W[i]: concat(W_, args(tolist)[i]),
    depends(W[i],tolist)),
  Wlist: makelist( W[i],i,N),
  if ff=1 then block(
    tmp: [curcomp(1),curcomp(2),curcomp(3)]
    )
  else if ff=2 then block(
    if get('ctensor,'version)=false then load(ctensor),
    set_ctensor_vars(init), christof(false),
    tmp: -[curcomp2(1),curcomp2(2),curcomp2(3)]
    ),
  if ff=1 then print("curl in physical basis"),
  if ff=2 then print("curl in coordinate basis"),
  tmp: expand( tmp ),
  define( funmake(dg_cur,Wlist), tmp )
);

/****************/
/* dg_diverg()  */
/****************/
/* Divergence in the new coordinates */
/* Need to call dg_metric(); first for this to work */
dg_diverg(ff):=block([W,N,tolist:cords_ot,tmp],
  if ff=1 then print("divergence in physical basis"),
  if ff=2 then print("divergence in coordinate basis"),
  if ff#1 and ff#2 then return(print("Arg must be (1) physical basis or (2) coordinate basis")),
  if scrootg=0 then dg_metric(init),
  N:length(tolist),
  for i: 1 thru N do ( W[i]: concat(W_, args(tolist)[i]),
    depends(W[i],tolist) ),
  Wlist: makelist( W[i],i,N),
  if ff=1 then tmp: sum( diff( scrootg* W[i]/sqrt(g[i,i]),args(tolist)[i]), i,1,N)/scrootg
  else if ff=2 then tmp: sum( diff( scrootg* W[i],args(tolist)[i]), i,1,N)/scrootg,
  define( funmake(dg_div,Wlist), expand(tmp) )
);

/*************/
/* dg_grad() */
/*************/
dg_grad(ff):=block([N,F,tolist:cords_ot,tmp],

  if scrootg=0 then dg_metric(init),
  if ff=1 then print("gradient in physical basis"),
  if ff=2 then print("gradient in coordinate basis"),
  if ff#1 and ff#2 then return(print("Arg must be (1) physical basis or (2) coordinate basis")),
  N:length(tolist),
  depends(F,tolist),
  hats:makelist( concat(e_,cords_ot[i]),i,N),
  if ff=1 then tmp: sum( diff( F/sqrt(g[i,i]),args(tolist)[i])*hats[i], i,1,N)
  else if ff=2 then tmp: sum( diff( F,args(tolist)[i])*hats[i], i,1,N),
  define( funmake(dg_gra,[F]), expand(trigsimp(tmp) ) )
)$
/* compute the gradient in new coords  */
/*
dg_grad_old():=block([N,F,diffmx,T1,T2,hats],
  run_checks(),
  N:length(cords_in),
  diffmx:makelist( 'diff(F,cords_ot[i]),i,N),
  hats:makelist( concat(e_,cords_ot[i]),i,N),
  T1:makelist(0,i,N),
  dg_jacobian(),
  Jitn: transpose( row_norm(Jinv) ),
  for i: 1 thru N do
    for j:1 thru N do
      T1[i]:T1[i]+diffmx[j]*Jinv[j,i],
  T2:makelist(0,i,N),
  for i:1 thru N do
    for j:1 thru N do
      T2[i]:T2[i]+hats[j]*Jitn[i,j],
  /* display(T1,T2,hats), */
  gra: sum(T1[i]*T2[i],i,1,N),
  gra:trigsimp(gra),
  gra:expand(gra),
  define( funmake(dg_gra,[F]) , gra )
);
*/

/****************/
/* dg_laplac()  */
/****************/
/* Laplacian in the new coordinates */
/* Need to call dg_metric(); first for this to work */
dg_laplac():=block([F,N,tolist:cords_ot,tmp,M],
  if scrootg=0 then dg_metric(init),
  N:length(tolist),
  depends(F,tolist),
  M: zeromatrix(N,N),
  ginv: invert(g),
  for i: 1 thru N do
    for j: 1 thru N do
        M[i,j]: diff( scrootg * ginv[i,j] * diff(F, args(tolist)[j] ) ,
        args(tolist)[i] ) / scrootg,
      M: ratsimp(M),
      L: sum( sum( M[i,j], i, 1, N) , j, 1, N),
      L: trigsimp(L),
      L: ev(L, collectterms, ratsimp),
  define( funmake(dg_lap,[F]) , expand(L) )
);


/************/
/* dg_ffc() */
/************/
/*
This function takes three arguments:
    1. cfunc: Euclidean coordinate functions in terms of
        curvilinear coordinates or other coordinates.
    2. coords: A list of the new coordinates, e.g. r,theta,phi
    3. constraint equation(s) imposed after calculating
        the attitude matrix, e.g. [r=1]
The function ffc outputs:
    1. The attitude matrix in 'A'
    2. The connection coefficients in 'omega'
    3. The dual 1-forms in 'th'
*/

/* The rows of the matrix A are, e.g.:
d/dr=  dr/dx, dr/dy, dr/dz
d/dth= dth/dx, dth/dy, dth/dz,...
These need to be normalized to get the correct
connection coefficients. */

dg_ffc([seq]):=block([cfunc:cords_tr,coords:cords_ot,i,j,dA,rmag,dx,dim,Ktmp],
    dim:length(coords),
    A:zeromatrix(dim,dim),
    dA:zeromatrix(dim,dim),
    rmag:zeromatrix(1,dim),
    dx:zeromatrix(dim,1),
    TT:zeromatrix(dim,dim),
    DD:zeromatrix(dim,dim),
    KK:zeromatrix(dim,dim),
    
    for i: 1 thru dim do  /* compute the coordinate differentials */
        dx[i,1]: diff(cfunc[i]),
    
    for i: 1 thru dim do /* construct the attitude matrix */
        for j: 1 thru dim do
            A[i,j]: diff(cfunc[j],coords[i]),
    
    A:subst(seq,A), /* put in any restrictions here, e.g. r=1 */
    
    A:row_norm(A), /* normalize the rows */
    dA: matrixmap(diff,A),
    thi: trigsimp( A . dx ), /* these are the theta_i dual forms */
    Omega: trigsimp( dA . transpose(A) ),
    
    /* Compute the structural equations */
    for i: 1 thru dim do
      for j: 1 thru i do
        ( TT[i,j]:TT[j,i]:thi[i].thi[j],
          DD[i,j]:DD[j,i]:expand(diff(Omega[i,j])),
          KK[i,j]:KK[j,i]:rhs( solve(DD[i,j]=Ktmp*TT[i,j],Ktmp)[1]) ),

    done
)$

/*********************/
/*  dg_kill();       */
/*********************/
/* Compute the Killing equations */
dg_kill(dis):=block([i,j,mu,nu,sg,dim:length(cords_ot)],
    declare_index_properties(xi,[postsuperscript]),
    killeq:zeromatrix(dim,dim),
    for mu: 1 thru dim do
        for nu: 1 thru dim do
            killeq[mu,nu]: sum(g[mu,sg]*'diff(xi[cords_ot[sg]],cords_ot[nu]),sg,1,dim)+
            sum(g[sg,nu]*'diff(xi[cords_ot[sg]],cords_ot[mu]),sg,1,dim)+
            sum(xi[cords_ot[sg]]*diff(g[mu,nu],cords_ot[sg]),sg,1,dim),
   if dis = show then
      for i:1 thru dim do
         for j:1 thru i do
            display(killeq[j,i])
)$
