(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("cord_in" . ("dgeom.info" 3803 92 "Functions and Variables for dgeom"))
("cord_ot" . ("dgeom.info" 3900 93 "Functions and Variables for dgeom"))
("cord_tr" . ("dgeom.info" 3998 181 "Functions and Variables for dgeom"))
("dg_cords" . ("dgeom.info" 4703 1126 "Functions and Variables for dgeom"))
("dg_curl" . ("dgeom.info" 10861 2050 "Functions and Variables for dgeom"))
("dg_derivs" . ("dgeom.info" 6048 1417 "Functions and Variables for dgeom"))
("dg_diverg" . ("dgeom.info" 12932 1120 "Functions and Variables for dgeom"))
("dg_ffc" . ("dgeom.info" 15500 1794 "Functions and Variables for dgeom"))
("dg_grad" . ("dgeom.info" 10064 784 "Functions and Variables for dgeom"))
("dg_kill" . ("dgeom.info" 17323 1274 "Functions and Variables for dgeom"))
("dg_laplac" . ("dgeom.info" 14077 1398 "Functions and Variables for dgeom"))
("dg_metric" . ("dgeom.info" 7490 2529 "Functions and Variables for dgeom"))
("dg_minkowski" . ("dgeom.info" 4188 494 "Functions and Variables for dgeom"))
("get_ctensor_vars" . ("dgeom.info" 18614 416 "Functions and Variables for dgeom"))
("set_ctensor_vars" . ("dgeom.info" 19063 1875 "Functions and Variables for dgeom"))
("show_cords" . ("dgeom.info" 5862 165 "Functions and Variables for dgeom"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Functions and Variables for dgeom" . ("dgeom.info" 3727 16899))
("Introduction to package dgeom" . ("dgeom.info" 751 2760))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
