(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("cord_in" . ("dgeom.info" 2517 92 "Functions and Variables for dgeom"))
("cord_ot" . ("dgeom.info" 2614 93 "Functions and Variables for dgeom"))
("cord_tr" . ("dgeom.info" 2712 181 "Functions and Variables for dgeom"))
("dg_cords" . ("dgeom.info" 4297 255 "Functions and Variables for dgeom"))
("dg_derivs" . ("dgeom.info" 4573 1417 "Functions and Variables for dgeom"))
("dg_diverg" . ("dgeom.info" 8943 1119 "Functions and Variables for dgeom"))
("dg_ffc" . ("dgeom.info" 11510 1794 "Functions and Variables for dgeom"))
("dg_grad" . ("dgeom.info" 8118 812 "Functions and Variables for dgeom"))
("dg_kill" . ("dgeom.info" 13333 1274 "Functions and Variables for dgeom"))
("dg_laplac" . ("dgeom.info" 10087 1398 "Functions and Variables for dgeom"))
("dg_metric" . ("dgeom.info" 6015 2062 "Functions and Variables for dgeom"))
("dg_minkowski" . ("dgeom.info" 2902 1188 "Functions and Variables for dgeom"))
("get_ctensor_vars" . ("dgeom.info" 14624 416 "Functions and Variables for dgeom"))
("set_ctensor_vars" . ("dgeom.info" 15073 1661 "Functions and Variables for dgeom"))
("show_cords" . ("dgeom.info" 4111 165 "Functions and Variables for dgeom"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Functions and Variables for dgeom" . ("dgeom.info" 2441 14017))
("Introduction to package dgeom" . ("dgeom.info" 755 1512))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
