(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("cord_in" . ("dgeom.info" 3803 92 "Functions and Variables for dgeom"))
("cord_ot" . ("dgeom.info" 3900 93 "Functions and Variables for dgeom"))
("cord_tr" . ("dgeom.info" 3998 695 "Functions and Variables for dgeom"))
("dg_cords" . ("dgeom.info" 5615 1642 "Functions and Variables for dgeom"))
("dg_curl" . ("dgeom.info" 26123 3126 "Functions and Variables for dgeom"))
("dg_derivs" . ("dgeom.info" 7480 1417 "Functions and Variables for dgeom"))
("dg_diverg" . ("dgeom.info" 29282 2042 "Functions and Variables for dgeom"))
("dg_ffc" . ("dgeom.info" 33590 1794 "Functions and Variables for dgeom"))
("dg_grad" . ("dgeom.info" 24121 1977 "Functions and Variables for dgeom"))
("dg_jacobian" . ("dgeom.info" 8922 290 "Functions and Variables for dgeom"))
("dg_kill" . ("dgeom.info" 35413 1433 "Functions and Variables for dgeom"))
("dg_laplac" . ("dgeom.info" 31361 1887 "Functions and Variables for dgeom"))
("dg_metric" . ("dgeom.info" 9229 9279 "Functions and Variables for dgeom"))
("dg_minkowski" . ("dgeom.info" 4734 848 "Functions and Variables for dgeom"))
("ds2_to_lg" . ("dgeom.info" 18565 2178 "Functions and Variables for dgeom"))
("get_ctensor_vars" . ("dgeom.info" 20858 416 "Functions and Variables for dgeom"))
("set_ctensor_vars" . ("dgeom.info" 21307 2243 "Functions and Variables for dgeom"))
("show_cords" . ("dgeom.info" 7294 165 "Functions and Variables for dgeom"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Functions and Variables for dgeom" . ("dgeom.info" 3727 32663))
("Introduction to package dgeom" . ("dgeom.info" 751 2760))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
